name: Testoutput
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    outputs:
      secret: ${{ steps.setup-secret.outputs.secret }}
    steps:
        - name: Setup secret
          id: setup-secret
          shell: pwsh
          run: |
            $secret = "SuperSecret"
            echo "::set-output name=secret::$secret"
  build:
    name: Build
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Run tests
        shell: pwsh
        env:
          SomeEnv: ${{ needs.setup.outputs.secret }}          
        run: echo ${{ needs.setup.outputs.secret }} 

  cleanup:
    runs-on: ubuntu-latest
    if: ${{ always() }}
    needs: [setup, build]
    steps:
      - name: Teardown
        if: ${{ needs.setup.outputs.secret != '' }}
        shell: pwsh        
        run: echo ${{ needs.setup.outputs.secret }} 
